//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip_Database_Deployment_Week8_WebAPIcs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public string authorId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int authorTaxFileNumber { get; set; }
    }
}
