CREATE TABLE [dbo].[Book]
(
	[ISBN] INT NOT NULL PRIMARY KEY,
	[title] NCHAR (100) NOT NULL,
	[authorId] VARCHAR(20) NOT NULL,
	[firstName] NCHAR(100) NOT NULL,
	[lastName] NCHAR(100) NOT NULL,
	[authorTaxFileNumber] INT NOT NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY (ISBN),
	CONSTRAINT FK_AUTHORID FOREIGN KEY (authorId) REFERENCES Author(authorId),
	CONSTRAINT FK_FIRSTNAME FOREIGN KEY (firstName) REFERENCES Author(firstName),
	CONSTRAINT FK_LASTNAME FOREIGN KEY (lastName) REFERENCES Author(lastName),
	CONSTRAINT FK_AUTHORTAXFILENUMBER FOREIGN KEY (authorTaxFileNumber) REFERENCES Author(authorTaxFileNumber)

)
