CREATE TABLE [dbo].[Book]
(
	[ISBN] NVARCHAR(50) NOT NULL,
	[title] NVARCHAR(100) NOT NULL,
	[PublicationYear] INT NOT NULL, 
	[authorId] INT NOT NULL,
	[studentId] nvarchar(20) NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY (ISBN),
	CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (authorId) REFERENCES Author(authorId),
	CONSTRAINT FK_BOOK_STUDENT FOREIGN KEY (studentId) REFERENCES Student
)
