CREATE TABLE [dbo].[Book]
(
	[ISBN] INT NOT NULL,
	[title] NCHAR (100) NOT NULL,
	[PublicationYear] INT NOT NULL, 
	[authorId] VARCHAR(20) NOT NULL,
	[firstName] NCHAR(100) NOT NULL,
	[lastName] NCHAR(100) NOT NULL,
	[authorTaxFileNumber] INT NOT NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY (ISBN),
	CONSTRAINT FK_AUTHORID FOREIGN KEY (authorId) REFERENCES Author(authorId)

)
