CREATE TABLE [dbo].[Student]
(
	[studentId] NVARCHAR(20) NOT NULL,
	[firstName] NVARCHAR(100) NOT NULL,
	[lastName] NVARCHAR(100) NOT NULL,
	[email] NVARCHAR(100) NOT NULL,
	[mobileNumber] NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (studentId)
)
